### ISSUE TITLE
Gemfile.lock missing

### ISSUE THREAD

**Issue by Slookeur** [vsoch/notes-jekyll#5]
Dear Vanessa, 
this is Sébastien Le Roux, first thank you for your quick reply yesterday.
I followed your tutorial to convert latex documents to md, I think I got the hang of it, 
apart for the container part, also I noticed that in your tutorial you convert tex to html and not markdown.  

I am trying to use your template to visualize if my conversion from latex to md was successful, some part is ok,
some can be improved, not to mention that I a single (long) page absolutely not organized for a decent search for help. 
So I followed the instruction you provide but got an error at this point:
```
docker build -t notes-jekyll .
Sending build context to Docker daemon  69.82MB
Step 1/9 : FROM jekyll/jekyll:4.1.0
 ---> d11121e6548e
Step 2/9 : WORKDIR /srv/jekyll
 ---> Using cache
 ---> 9c6c294605cf
Step 3/9 : COPY Gemfile .
 ---> Using cache
 ---> 915a597fed7c
Step 4/9 : COPY Gemfile.lock .
COPY failed: file not found in build context or excluded by .dockerignore: stat Gemfile.lock: file does not exist

```
Thanks in advance for your lights.

Sébastien

**Comment by vsoch** [comment]
That’s generated when you do bundle exec jekyll serve, do either you can do that on the host to make the file or just comment out the line. Also make sure you look at the RSE ops knowledge repo to see the latex conversion, first to markdown and then html.

**Comment by Slookeur** [comment]
Dear @vsoch, 
I am getting more familiar with the tools available on github to build pages, mkdocs in really easy to use but is limited for LaTeX stuff, If only I could successfully build a Jekyll example to compare both ... I tried several times to run your notes-jekyll example but each time I try to do it gthub fails to build the pages and because of the 'cite', 'quote' or else instructions ... I could get rid of all instructions in the related pages but that would defy the purpose of this tool ... so could you please tell me what's wrong with my way of doing things (I cloned your template here: https://github.com/Slookeur/Atomes-notes). 
Thanks in advance for your help, best regards.

**Comment by vsoch** [comment]
Just run bundle exec jekyll serve locally to generate the lock file.

**Comment by Slookeur** [comment]
Dear Vanessa, this message to let you know that I published my documentation (https://slookeur.github.io/Atomes-doc/) 
I needed some time to understand how everything is working from GitHub / GitHub Pages / Jekyll ... and so on ...
I think that I have the hang of it now and your tutorial / work on GitHub helped me a lot. 
So I wanted to thank you for your help, and that I very much appreciate that you took the time to write down those tutorials
to help others like my self. Please keep up your good vibe ;-)

All the best !

**Comment by vsoch** [comment]
Awesome! Glad to help. All the best to you too!
