### ISSUE TITLE
File in '_posts' does not render

### ISSUE THREAD

**Issue by JackYansongLi** [vsoch/notes-jekyll#6]
I tried to use this template recently, and it works fine in the main page. But, when clicking the link to the pages in _posts files, the page does not render in my local host.

**Comment by vsoch** [comment]
Can you be more specific about your issue?  I just cloned the repo fresh:

```bash
$ bundle install
$ bundle exec jekyll serve
```
And I see both posts that are provided as examples. 

![image](https://user-images.githubusercontent.com/814322/166393356-348d3dde-9824-40bb-a363-a34eab53d40c.png)


![image](https://user-images.githubusercontent.com/814322/166393390-64109d2d-b9ad-4808-92e8-774ab2832475.png)

I'm going to need enough to reproduce your error to help, or minimally more detail / description / screenshots beyond "does not render."

**Comment by JackYansongLi** [comment]
![1651542585(1)](https://user-images.githubusercontent.com/53420718/166393768-63717133-b6cc-4a12-aff4-7f912b7c6b3b.jpg)
I am using this template on Windows. I changed several command in .yml and gemfile

**Comment by vsoch** [comment]
ah gotcha - so I can't easily reproduce on Windows (I imagine there are others issues) but glad that you figured it out! For reference, this is what it's supposed to look like: https://vsoch.github.io/notes-jekyll/how-to-write-notes

**Comment by Haggitt** [comment]
source 'https://rubygems.org'
group :jekyll_plugins do
    #gem 'github-pages'
    gem 'jekyll-paginate'
    gem 'jekyll-scholar'
    gem 'webrick'
    gem 'jekyll-feed'
    gem 'jekyll-seo-tag'
    gem 'jekyll-sitemap'
     gem 'jekyll-archives'
    gem 'jekyll-redirect-from'
   gem 'wdm', '>= 0.1.0' if Gem.win_platform?
end

baseurl: ""

**Comment by JackYansongLi** [comment]
I fixed this problem by running all the command on WSL (Windows subsystem for Linux). Thanks for your template. I will use it to build my personal blog during my Ph.D.

**Comment by vsoch** [comment]
Awesome! Yes I've heard Windows (WSL) is pretty good. Congrats on (starting?) your PhD, or at least the personal blog for it! :partying_face:
