### ISSUE TITLE
Displayed formula does not render

### ISSUE THREAD

**Issue by JackYansongLi** [vsoch/notes-jekyll#7]
See section 6.2 and 6.2.3, the displayed formula inside $$ $$ does not render.
I tried to run this command on my computer and get the same result.

**Comment by vsoch** [comment]
Taking a look!

**Comment by JackYansongLi** [comment]
for usual $$ $$, it works fine. But with ~~~ latex and some latex command such as \label, the displayed formula will not render.

**Comment by vsoch** [comment]
yeah I fixed it about 30 minutes ago (and it's pushed) just struggling with fixing a bug in the deploy script. You should be able to use the example in main though!

**Comment by vsoch** [comment]
okay should finally be deployed! It's amazing how much ruby / jekyll can change to break a build.

**Comment by vsoch** [comment]
Feel free to open a pull request if you find issues that you'd like to fix. Thanks for reporting, and also please close if the rendering now looks okay to you. It's basically mathjax and the blocks with "latex" and the squiggles were intended to show what the raw latex in the markdown should look like, but it didn't do a proper job.
