### ISSUE TITLE
Problem using the template

### ISSUE THREAD

**Issue by JackYansongLi** [vsoch/notes-jekyll#9]
When GitHub built this template from my repository, it gets the following error in the "deploy" process.

remote: Write access to repository not granted.
fatal: unable to access 'https://github.com/Haggitt/Optimization-Notes.git/': The requested URL returned error: 403
Error: Process completed with exit code 128.

**Comment by JackYansongLi** [comment]
I solved the above problem by setting Workflow permissions to Read and write permissions.
It successfully builds the website but still have the problem about the citation. 
It says
```
The tag cite on line 5 in _posts/2020-11-27-registration.md is not a recognized Liquid tag.
```

**Comment by vsoch** [comment]
> When GitHub built this template from my repository, it gets the following error in the "deploy" process.

Yes if your repository is private you need to do a clone with a token and likely git@ url.

> The tag cite on line 5 in _posts/2020-11-27-registration.md is not a recognized Liquid tag.

I don't think you've installed the gem - are you using the most recent workflow or an older one? 

https://github.com/vsoch/notes-jekyll/blob/main/.github/workflows/build.yml

I had to do updates last night because the old one would not build. I can't see your repo so I can't tell.

**Comment by JackYansongLi** [comment]
I am using the new one, it now successfully build the website, but I get a 404 when I try to watch the website from the url. I didn't see the deployment in my action section. I made my repo. public now, so you can see the issue.

**Comment by Haggitt** [comment]
I made it public now

**Comment by JackYansongLi** [comment]
![image](https://user-images.githubusercontent.com/53420718/166552487-07d03819-9d14-4ef9-8e1f-d19c58adf51f.png)

**Comment by vsoch** [comment]
Go to your repository settings and make sure that Actions are enabled (I don't see the tab so I think they may not be!)

**Comment by JackYansongLi** [comment]
It is enabled.

**Comment by vsoch** [comment]
And GitHub pages is enabled for the gh-pages branch?

**Comment by JackYansongLi** [comment]
I don't understand.

**Comment by JackYansongLi** [comment]
![image](https://user-images.githubusercontent.com/53420718/166560661-53c19c30-7d1e-4f42-bed2-b08b50cc8462.png)

**Comment by vsoch** [comment]
So GitHub pages needs to be "turned on" for a repository - and you can do that by going to Settings -> Pages -> Select "gh-pages" -> Save

It should look like this:

![image](https://user-images.githubusercontent.com/814322/166561232-b96ace27-5f63-49f5-8256-988e4f7a89d8.png)

**Comment by vsoch** [comment]
Once pages is on, every time the workflow pushes to gh-pages you should see a new workflow run by the github pages bot that looks like this: 
![image](https://user-images.githubusercontent.com/814322/166561373-11bb6a73-dbd3-4dd1-b8dc-e3862fcabd26.png)

**Comment by JackYansongLi** [comment]
It works!!! Thanks! I am new to the GitHub, and it costs a lot of time to fix these tiny problems. You helped me a lot, thanks again!

**Comment by vsoch** [comment]
Of course! Happy to help :) Note that when you first deploy pages sometimes it takes a few minutes for the style files to catch up, so it looks wonky. If it still remains like that after maybe 10 minutes I usually try another push, confirm that whatever file is missing is indeed in the gh-pages branch, and make sure my browser isn't caching the page.

**Comment by vsoch** [comment]
one bug I see in your page that should be easy to fix is that you need to update the baseurl to be your repository name, e.g., notes-jekyll -> Optimization-Notes here: https://github.com/Haggitt/Optimization-Notes/blob/87051712ec5cb9dfb4c3b6103702d6948d520692/_config.yml#L3. You also probably want to look through the other metadata in that file and make sure it's correct for your repo!

**Comment by JackYansongLi** [comment]
Got! I will keep using this template and to see where needs to be fixed.
